FROM docker.io/redhat/ubi9:9.3



ARG GTEST_VERSION=1.15.2
ARG BOOST_VERSION_DOT=1.86.0
ARG BOOST_VERSION_UNDERSCORE=1_86_0
ARG BENCHMARK_VERSION=1.9.0



# not exist: wireshark-cli, google-noto-sans-fonts, tcsh, csh 
# not exist groups: "c-development" "development-tools"
# already installed: ca-certificates util-linux iproute openssl tar
# to check: gdb-server tcpdump  glibc libstdc++ libstdc++-docs libgcc glibc-langpack-en gcc gcc-c++ gdb sudo openssl openssl-devel net-tools bind-utils gdb-gdbserver ipcgull-devel
# xterm meld  nfs-utils tree ansible hostname cifs-utils samba-client perf binutils-devel elfutils-devel elfutils-libelf-devel texinfo zlib-devel rsync bat ngrep hiera lsyncd sshpass lcov jq ccache lapack-devel dwarves


# should be add tcsh csh


google-noto-sans-fonts && \
dnf clean all && \
mkdir -p /var/run/sshd


# checked: 
RUN dnf -y --setopt=sslverify=false clean all; dnf -y update ; dnf -y update --refresh  && \ 
    dnf -y --setopt=sslverify=false --allowerasing install \
    openssh-server
    openssh-clients
    fontconfig
    procps-ng
    gdb
    file
    hostname
    net-tools
    nmap
    strace
    zip
    nano
    pciutils
    wget
    less
    git
    cmake
    ninja-build
    valgrind
    libcurl
    pip
    bash
    glibc-devel
    libstdc++-devel
    perl
    which
    gzip 
    sudo
    tar
    elfutils
    gcc
    gcc-c++
    python3-devel
    # zeev packages
    man --setopt='tsflags='
    jq

    && \
    dnf clean all && \
    mkdir -p /var/run/sshd


# Give to root empty password
RUN echo "root:1" | chpasswd

# rita requirements 
# pywin package doesnt exist
# pip3 install requests==2.30.0
# pip3 install ftputil==5.0.4
# pip3 install configparser==5.0.2
# pip3 install colorama==0.4.6
# pip3 install docxtpl==0.15.2
# pip3 install jira==3.5.0
# pip3 install pandas==2.0.1
# pip3 install junit2html==30.1.3
# pip3 install junit-xml==1.9

# Install pip packages
RUN pip3 install --no-cache-dir 


RUN dnf update -y && \
    dnf clean all -y && \
    echo && \
    echo Set gcc alternatives && \
    alternatives --install /usr/local/bin/gcc gcc  /usr/bin/gcc 1 \
    --slave /usr/local/bin/g++ g++ /usr/bin/g++ \
    --slave /usr/local/bin/gcc-ar gcc-ar /usr/bin/gcc-ar \
    --slave /usr/local/bin/gcc-nm gcc-nm /usr/bin/gcc-nm \
    --slave /usr/local/bin/gcc-ranlib gcc-runlib /usr/bin/gcc-ranlib  && \
    alternatives --install /usr/local/bin/gcc gcc /usr/local/gcc/gcc8.5/bin/gcc-8.5 20 \
    --slave /usr/local/bin/g++ g++ /usr/local/gcc/gcc8.5/bin/g++-8.5 \
    --slave /usr/local/bin/gcc-ar gcc-ar /usr/local/gcc/gcc8.5/bin/gcc-ar-8.5 \
    --slave /usr/local/bin/gcc-nm gcc-nm /usr/local/gcc/gcc8.5/bin/gcc-nm-8.5 \
    --slave /usr/local/bin/gcc-ranlib gcc-runlib /usr/local/gcc/gcc8.5/bin/gcc-ranlib-8.5  && \
    alternatives --set gcc /usr/bin/gcc

# Install Boost
RUN pushd /tmp/ && \
	echo gcc version: && \
	gcc --version && \
	echo g++ version: && \	
	g++ --version && \	
	wget https://archives.boost.io/release/${BOOST_VERSION_DOT}/source/boost_${BOOST_VERSION_UNDERSCORE}.tar.gz  && \	
    tar zxf boost_${BOOST_VERSION_UNDERSCORE}.tar.gz && \
	cd boost_${BOOST_VERSION_UNDERSCORE} && \
	echo Start boost installation: && \	
	echo Call bootstrap.sh: && \
	./bootstrap.sh --with-toolset=gcc && \
	echo Call b2 install: && \
	./b2 install && \
	cd /tmp/ && \
	rm -rf zxvf boost_${BOOST_VERSION_UNDERSCORE}.tar.gz && \
	rm -rf boost_${BOOST_VERSION_UNDERSCORE} && \
	popd

# Install google test
RUN pushd /tmp/ && \
    wget https://github.com/google/googletest/releases/download/v${GTEST_VERSION}/googletest-${GTEST_VERSION}.tar.gz  && \
	tar zxvf googletest-${GTEST_VERSION}.tar.gz && \
	mkdir googleBuild  && \
	cd googleBuild  && \
	cmake /tmp/googletest-${GTEST_VERSION}  && \
	cmake -Dgtest_build_samples=ON /tmp/googletest-${GTEST_VERSION}  && \
	make install && \
	make clean	 && \
	cd /tmp/	 && \
	rm -f googletest-${GTEST_VERSION}.tar.gz && \
	rm -rf googletest-${GTEST_VERSION} && \
	rm -rf googleBuild && \
	popd

## Install google benchmark
RUN pushd /tmp/ && \
	mkdir benchmark_install && cd benchmark_install && \
    wget https://github.com/google/benchmark/archive/refs/tags/v${BENCHMARK_VERSION}.tar.gz  && \
    tar zxvf v${BENCHMARK_VERSION}.tar.gz && \
	cd benchmark-${BENCHMARK_VERSION}  && \
	cmake -E make_directory "build"  && \
	cmake -DBENCHMARK_DOWNLOAD_DEPENDENCIES=on -DBENCHMARK_ENABLE_ASSEMBLY_TESTS=off -DCMAKE_BUILD_TYPE=Release -S . -B "build" && \
	cmake --build "build" --config Release -- "-j20" && \
	cmake -E chdir "build" ctest --build-config Release && \
	sudo cmake --build "build" --config Release --target install && \
	cmake --build "build" --config Release --target clean && \
	cd /tmp/	 && \
	rm -rf benchmark_install && \
	popd
    
### install sonarqube
RUN cd /usr/bin/ && \
	wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip && \
	unzip sonar-scanner-cli-4.6.2.2472-linux.zip && \
	rm -f sonar-scanner-cli-4.6.2.2472-linux.zip && \
	/usr/bin/sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -v 





